matrix:
  exclude:
    - language: ruby
      dist: precise
  include:
    - language: java
      jdk: openjdk8
      script: 
        - make
      after_success:
        - make coverage
      cache:
        directories:
        - "$HOME/.m2"
      dist: trusty
